import { Deck } from '../types/flashcard';

export const SAMPLE_DECKS: Deck[] = [
  {
    id: 'deck-c1-c2-vocab',
    title: 'Từ Vựng Theo Chủ Đề C1 - C2 Nâng Cao',
    description: 'Bộ từ vựng học thuật & đời sống cao cấp C1/C2 (Academic & Advanced Vocabulary) chuẩn CEFR & IELTS 7.5 - 8.5+.',
    language: 'en-US',
    targetLanguage: 'vi-VN',
    category: 'Từ vựng C1-C2',
    tags: ['C1', 'C2', 'IELTS', 'Academic', 'Advanced'],
    color: '#6366f1',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    cards: [
      {
        id: 'c1-01',
        term: 'Ubiquitous',
        phonetic: '/juːˈbɪk.wə.t̬əs/',
        partOfSpeech: 'adjective',
        definition: 'Có mặt ở khắp mọi nơi cùng một lúc, vô cùng phổ biến',
        example: 'Smartphones and social media apps have become ubiquitous in modern society.',
        exampleTranslation: 'Điện thoại thông minh và các ứng dụng mạng xã hội đã trở nên hiện diện ở khắp mọi nơi trong xã hội hiện đại.',
        grammarPattern: 'become / remain ubiquitous in sth',
        notes: 'Đồng nghĩa: omnipresent, pervasive, universal. Mẹo nhớ: "U-bi-quit" -> ở đâu bạn muốn quit cũng thấy nó!',
        tags: ['C1', 'Academic', 'Technology'],
        starred: true,
        repetition: 2,
        interval: 3,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 3,
        lapses: 0,
      },
      {
        id: 'c1-02',
        term: 'Exacerbate',
        phonetic: '/ɪɡˈzæs.ɚ.beɪt/',
        partOfSpeech: 'verb',
        definition: 'Làm trầm trọng thêm, khiến một vấn đề/tình hình trở nên tồi tệ hơn',
        example: 'The ongoing energy shortage has exacerbated the country’s economic crisis.',
        exampleTranslation: 'Tình trạng thiếu hụt năng lượng kéo dài đã làm trầm trọng thêm cuộc khủng hoảng kinh tế của quốc gia.',
        grammarPattern: 'exacerbate a problem / crisis / situation',
        notes: 'Đồng nghĩa: aggravate, worsen. Trái nghĩa: alleviate, mitigate.',
        tags: ['C1', 'C2', 'IELTS Writing', 'Formal'],
        starred: false,
        repetition: 1,
        interval: 1,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 2,
        lapses: 0,
      },
      {
        id: 'c1-03',
        term: 'Pivotal',
        phonetic: '/ˈpɪv.ə.t̬əl/',
        partOfSpeech: 'adjective',
        definition: 'Mang tính then chốt, có tầm quan trọng quyết định chiều hướng phát triển',
        example: 'Technological innovation plays a pivotal role in maintaining economic competitiveness.',
        exampleTranslation: 'Đổi mới công nghệ đóng vai trò then chốt trong việc duy trì năng lực cạnh tranh kinh tế.',
        grammarPattern: 'play a pivotal role / part in (doing) sth',
        notes: 'Gốc từ: "pivot" (trục xoay) -> vật làm trụ quyết định tất cả.',
        tags: ['C1', 'Academic', 'Writing'],
        starred: true,
        repetition: 3,
        interval: 6,
        easeFactor: 2.6,
        dueDate: new Date().toISOString(),
        reviewCount: 4,
        lapses: 0,
      },
      {
        id: 'c1-04',
        term: 'Ephemeral',
        phonetic: '/ɪˈfem.ər.əl/',
        partOfSpeech: 'adjective',
        definition: 'Phù du, ngắn ngủi, chỉ tồn tại trong một khoảng thời gian rất ngắn',
        example: 'Social media fame is often ephemeral, fading as soon as trends change.',
        exampleTranslation: 'Sự nổi tiếng trên mạng xã hội thường chỉ là phù du, tan biến ngay khi các xu hướng thay đổi.',
        grammarPattern: 'ephemeral nature / fame / pleasure',
        notes: 'Đồng nghĩa: transient, fleeting, short-lived. Trái nghĩa: perpetual, enduring.',
        tags: ['C2', 'Literature', 'Philosophy'],
        starred: false,
        repetition: 0,
        interval: 1,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 0,
        lapses: 0,
      },
      {
        id: 'c1-05',
        term: 'Mitigate',
        phonetic: '/ˈmɪt.ə.ɡeɪt/',
        partOfSpeech: 'verb',
        definition: 'Làm dịu bớt, giảm thiểu mức độ nghiêm trọng hoặc tác hại',
        example: 'Governments must implement prompt measures to mitigate the impacts of climate change.',
        exampleTranslation: 'Các chính phủ phải thực thi các biện pháp kịp thời nhằm giảm thiểu tác động của biến đổi khí hậu.',
        grammarPattern: 'mitigate risks / damage / effects / impact',
        notes: 'Đồng nghĩa: alleviate, lessen, attenuate.',
        tags: ['C1', 'Environment', 'Policy', 'IELTS'],
        starred: false,
        repetition: 1,
        interval: 1,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 1,
        lapses: 0,
      },
      {
        id: 'c1-06',
        term: 'Pragmatic',
        phonetic: '/præɡˈmæt.ɪk/',
        partOfSpeech: 'adjective',
        definition: 'Thực tế, thực dụng, dựa trên điều kiện thực tế thay vì lý thuyết viển vông',
        example: 'We need a pragmatic approach to solve this budgetary dilemma efficiently.',
        exampleTranslation: 'Chúng ta cần một cách tiếp cận thực tế để giải quyết tình thế khó xử về ngân sách này một cách hiệu quả.',
        grammarPattern: 'a pragmatic approach / solution / attitude to sth',
        notes: 'Đồng nghĩa: practical, realistic, down-to-earth.',
        tags: ['C1', 'Business', 'Academic'],
        starred: false,
        repetition: 2,
        interval: 3,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 2,
        lapses: 0,
      },
      {
        id: 'c1-07',
        term: 'Conundrum',
        phonetic: '/kəˈnʌn.drəm/',
        partOfSpeech: 'noun',
        definition: 'Tình thế tiến thoái lưỡng nan, một câu hỏi/vấn đề hóc búa rất khó giải quyết',
        example: 'Arranging childcare while balancing full-time work remains a major conundrum for working parents.',
        exampleTranslation: 'Thu xếp việc chăm sóc con cái trong khi vẫn cân bằng công việc toàn thời gian vẫn là một bài toán hóc búa đối với các bậc phụ huynh đi làm.',
        grammarPattern: 'pose / face a conundrum',
        notes: 'Đồng nghĩa: dilemma, quandary, puzzle.',
        tags: ['C2', 'Formal', 'Discussion'],
        starred: true,
        repetition: 0,
        interval: 1,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 0,
        lapses: 0,
      },
      {
        id: 'c1-08',
        term: 'Paradigm shift',
        phonetic: '/ˈpær.ə.daɪm ʃɪft/',
        partOfSpeech: 'noun phrase',
        definition: 'Sự thay đổi căn bản trong hệ tư tưởng, quan niệm hoặc phương thức tiếp cận',
        example: 'The emergence of artificial intelligence represents a paradigm shift in how knowledge work is conducted.',
        exampleTranslation: 'Sự xuất hiện của trí tuệ nhân tạo đại diện cho một bước chuyển hệ hình căn bản trong cách thức thực hiện công việc tri thức.',
        grammarPattern: 'a paradigm shift in sth',
        notes: 'Thường dùng trong văn cảnh khoa học, công nghệ và phát triển xã hội.',
        tags: ['C2', 'Technology', 'Philosophy', 'Essay'],
        starred: false,
        repetition: 1,
        interval: 1,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 1,
        lapses: 0,
      },
      {
        id: 'c1-09',
        term: 'Quintessential',
        phonetic: '/ˌkwɪn.təˈsen.ʃəl/',
        partOfSpeech: 'adjective',
        definition: 'Tinh túy, mang tính đại diện hoàn hảo nhất cho một phẩm chất hoặc phong cách',
        example: 'Afternoon tea at the Ritz is considered the quintessential British cultural experience.',
        exampleTranslation: 'Trà chiều tại khách sạn Ritz được coi là trải nghiệm văn hóa tinh túy, đặc trưng nhất của nước Anh.',
        grammarPattern: 'the quintessential example / embodiment of sth',
        notes: 'Từ gốc Latin "quinta essentia" (nguyên tố thứ năm tinh khiết nhất).',
        tags: ['C2', 'Culture', 'Descriptive'],
        starred: false,
        repetition: 0,
        interval: 1,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 0,
        lapses: 0,
      },
      {
        id: 'c1-10',
        term: 'Disseminate',
        phonetic: '/dɪˈsem.ə.neɪt/',
        partOfSpeech: 'verb',
        definition: 'Phổ biến, truyền bá rộng rãi (thông tin, kiến thức, ý tưởng)',
        example: 'Universities are dedicated to creating new knowledge and disseminating it widely to the public.',
        exampleTranslation: 'Các trường đại học luôn cống hiến cho việc kiến tạo tri thức mới và phổ biến rộng rãi tới cộng đồng.',
        grammarPattern: 'disseminate information / findings / ideas to sb',
        notes: 'Đồng nghĩa: circulate, distribute, broadcast.',
        tags: ['C1', 'Academic', 'Research'],
        starred: false,
        repetition: 1,
        interval: 2,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 1,
        lapses: 0,
      },
      {
        id: 'c1-11',
        term: 'Take something with a pinch of salt',
        phonetic: '/teɪk ˈsʌm.θɪŋ wɪð ə pɪntʃ əv sɑːlt/',
        partOfSpeech: 'idiom',
        definition: 'Tiếp nhận thông tin với sự hoài nghi lành mạnh, không tin tưởng 100%',
        example: 'Online gossip should always be taken with a pinch of salt before verifying the facts.',
        exampleTranslation: 'Những tin đồn vô căn cứ trên mạng luôn cần được tiếp nhận với sự thận trọng, dè dặt trước khi kiểm chứng sự thật.',
        grammarPattern: 'take sth with a pinch / grain of salt',
        notes: 'Mẹo nhớ: nêm chút muối vào lời nói để không bị nuốt trọn sự dối trá.',
        tags: ['C1', 'Idioms', 'Daily English'],
        starred: true,
        repetition: 2,
        interval: 4,
        easeFactor: 2.6,
        dueDate: new Date().toISOString(),
        reviewCount: 2,
        lapses: 0,
      },
      {
        id: 'c1-12',
        term: 'Turn a blind eye to',
        phonetic: '/tɝːn ə blaɪnd aɪ tuː/',
        partOfSpeech: 'idiom',
        definition: 'Nhắm mắt làm ngơ, cố tình giả vờ không thấy hành vi sai trái',
        example: 'Authorities cannot afford to turn a blind eye to widespread regulatory violations.',
        exampleTranslation: 'Các cơ quan chức năng không thể tiếp tục nhắm mắt làm ngơ trước những vi phạm quy định tràn lan.',
        grammarPattern: 'turn a blind eye to sth/sb',
        notes: 'Nguồn gốc: Đô đốc Nelson thời xưa áp ống nhòm vào bên mắt bị chột để lờ đi mệnh lệnh rút quân.',
        tags: ['C1', 'Idioms', 'Politics'],
        starred: false,
        repetition: 0,
        interval: 1,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 0,
        lapses: 0,
      },
    ],
  },
  {
    id: 'deck-c1-grammar',
    title: 'Cấu Trúc Ngữ Pháp Ngoại Ngữ C1 - C2 Hay Gặp',
    description: 'Bộ thẻ mẫu câu ngữ pháp nâng cao: Đảo ngữ (Inversion), Thể giả định (Subjunctive), Mệnh đề phân từ (Participle Clauses), Câu chẻ (Cleft sentences).',
    language: 'en-US',
    targetLanguage: 'vi-VN',
    category: 'Ngữ pháp C1-C2',
    tags: ['Grammar', 'C1', 'C2', 'Inversion', 'Writing'],
    color: '#06b6d4',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    cards: [
      {
        id: 'gram-01',
        term: 'Hardly / Scarcely ... when (Đảo ngữ)',
        phonetic: '/ˈhɑːrd.li ... wen/',
        partOfSpeech: 'grammar structure',
        definition: 'Vừa mới ... thì đã ... (Diễn tả hai hành động diễn ra liên tiếp trong quá khứ)',
        example: 'Hardly had the keynote speaker stepped onto the stage when thunderous applause erupted.',
        exampleTranslation: 'Diễn giả chính vừa mới bước lên sân khấu thì tiếng vỗ tay rền vang đã bùng nổ.',
        grammarPattern: 'Hardly / Scarcely + had + S + V(p.p) + when + S + V(past)',
        notes: 'Lưu ý: Mệnh đề đầu tiên luôn đảo trợ động từ "had" lên trước chủ ngữ. Đi với "when" (không đi với "than").',
        tags: ['Inversion', 'C1', 'Past Perfect'],
        starred: true,
        repetition: 1,
        interval: 2,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 2,
        lapses: 0,
      },
      {
        id: 'gram-02',
        term: 'No sooner ... than (Đảo ngữ)',
        phonetic: '/noʊ ˈsuː.nɚ ... ðæn/',
        partOfSpeech: 'grammar structure',
        definition: 'Ngay khi / Vừa mới ... thì ...',
        example: 'No sooner had we published the research article than we received feedback from scholars worldwide.',
        exampleTranslation: 'Chúng tôi vừa mới công bố bài nghiên cứu thì đã nhận được phản hồi từ các học giả trên toàn thế giới.',
        grammarPattern: 'No sooner + had + S + V(p.p) + than + S + V(past)',
        notes: 'Phân biệt: "No sooner" luôn đi cùng liên từ "than", khác với "Hardly ... when".',
        tags: ['Inversion', 'C1', 'Writing Task 2'],
        starred: false,
        repetition: 2,
        interval: 4,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 3,
        lapses: 0,
      },
      {
        id: 'gram-03',
        term: 'Cleft Sentence with "It" (Câu chẻ nhấn mạnh)',
        phonetic: '/ɪt ɪz ... ðæt/',
        partOfSpeech: 'grammar structure',
        definition: 'Chính ... mới là điều/người mà ... (Tập trung trọng tâm vào chủ ngữ, tân ngữ hoặc trạng ngữ)',
        example: 'It was her unyielding persistence, not sheer luck, that propelled the enterprise to global prominence.',
        exampleTranslation: 'Chính sự kiên trì không lay chuyển của cô ấy, chứ không phải may mắn thuần túy, đã đưa doanh nghiệp vươn tầm quốc tế.',
        grammarPattern: 'It is / was + [Thành phần nhấn mạnh] + that / who + [Mệnh đề]',
        notes: 'Rất hiệu quả trong bài luận IELTS Writing và phát biểu trang trọng để tạo điểm nhấn ngữ khí mạnh mẽ.',
        tags: ['Cleft Sentence', 'Emphasis', 'C1'],
        starred: true,
        repetition: 1,
        interval: 1,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 1,
        lapses: 0,
      },
      {
        id: 'gram-04',
        term: 'Subjunctive Mood with Demands (Thể giả định thức)',
        phonetic: '/səbˈdʒʌŋk.tɪv muːd/',
        partOfSpeech: 'grammar structure',
        definition: 'Cấu trúc giả định yêu cầu/đề xuất: động từ ở mệnh đề that luôn ở dạng nguyên mẫu không "to"',
        example: 'The ethics committee mandated that every clinical trial participant be thoroughly informed of potential risks.',
        exampleTranslation: 'Hội đồng y đức đã bắt buộc rằng mọi người tham gia thử nghiệm lâm sàng phải được thông báo kỹ lưỡng về các rủi ro tiềm ẩn.',
        grammarPattern: 'S + demand/mandate/insist/recommend + that + S + (should) + V-infinitive',
        notes: 'Lưu ý: Dù chủ ngữ là số ít (he, she, participant), động từ vẫn là nguyên mẫu (be, submit, do), không chia thì.',
        tags: ['Subjunctive', 'Formal', 'C2'],
        starred: false,
        repetition: 0,
        interval: 1,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        reviewCount: 0,
        lapses: 0,
      },
      {
        id: 'gram-05',
        term: 'Perfect Participle Clause (Mệnh đề phân từ hoàn thành)',
        phonetic: '/ˈhæv.ɪŋ + V(p.p)/',
        partOfSpeech: 'grammar structure',
        definition: 'Rút gọn mệnh đề chỉ nguyên nhân hoặc thứ tự thời gian đã hoàn tất trước hành động chính',
        example: 'Having meticulously analyzed the historical data, the economists forecasted an imminent market correction.',
        exampleTranslation: 'Sau khi đã phân tích tỉ mỉ các dữ liệu lịch sử, các nhà kinh tế học đã dự báo một đợt điều chỉnh thị trường sắp xảy ra.',
        grammarPattern: 'Having + V(p.p)..., S + V(past)',
        notes: 'Chủ ngữ của mệnh đề phân từ phải trùng với chủ ngữ của mệnh đề chính để tránh lỗi Dangling Modifier.',
        tags: ['Participle Clause', 'Sentence Reduction', 'C1', 'C2'],
        starred: true,
        repetition: 2,
        interval: 5,
        easeFactor: 2.6,
        dueDate: new Date().toISOString(),
        reviewCount: 2,
        lapses: 0,
      },
    ],
  },
];
